--SET REFERENTIAL_INTEGRITY FALSE;
--TRUNCATE TABLE FRIENDS_LIST      RESTART IDENTITY;
----TRUNCATE TABLE FILMS_GENRE  RESTART IDENTITY;
--TRUNCATE TABLE GENRES        RESTART IDENTITY;
--TRUNCATE TABLE LIKE_LIST   RESTART IDENTITY;
--TRUNCATE TABLE FILMS        RESTART IDENTITY;
--TRUNCATE TABLE RATING   RESTART IDENTITY;
--TRUNCATE TABLE USERS        RESTART IDENTITY;
--SET REFERENTIAL_INTEGRITY TRUE;

MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
VALUES (1,'Комедия'),
       (2,'Драма'),
       (3,'Мультфильм'),
       (4,'Триллер'),
       (5,'Документальный'),
       (6,'Боевик');

MERGE INTO RATING (RATING_ID, RATING_NAME)
VALUES (1,'G'),
       (2,'PG'),
       (3,'PG-13'),
       (4,'R'),
       (5,'NC-17');